version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # AMQP
      - "15672:15672"    # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    depends_on:
      - rabbitmq
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
      QUEUE_NAME: messages_queue
    ports:
      - "8001:8001"

  chat-service:
    build: ./chat-service
    container_name: chat-service
    depends_on:
      - rabbitmq
      - redis
    environment:
      PYTHONUNBUFFERED: 1
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
      QUEUE_NAME: messages_queue

      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8002:8002"