version: "3.8"

services:
  # ---------- Common Services ----------
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"      # AMQP
      - "15672:15672"    # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  # ---------- Auth-Service + DB ----------
  postgres-auth:
    image: postgres:latest
    container_name: postgres-auth
    restart: always
    environment:
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
      POSTGRES_DB: authdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data

  auth-service:
    build: ./auth-service
    container_name: auth-service
    restart: always
    depends_on:
      - postgres-auth
    environment:
      APP_ENV: development
      DATABASE_URL: postgresql://authuser:authpass@postgres-auth:5432/authdb
      ACCESS_SECRET_KEY: "access_secret_key"
    # If you want to expose port:
    # ports:
    #   - "8003:8003"

  # ---------- Chat-Service + DB ----------
  postgres-chat:
    image: postgres:latest
    container_name: postgres-chat
    restart: always
    environment:
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: chatpass
      POSTGRES_DB: chatdb
    ports:
      - "5434:5432"
    volumes:
      - postgres_chat_data:/var/lib/postgresql/data

  chat-service:
    build: ./chat-service
    container_name: chat-service
    restart: always
    depends_on:
      - rabbitmq
      - redis
      - postgres-chat
    environment:
      PYTHONUNBUFFERED: 1
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
      QUEUE_NAME: messages_queue
      DATABASE_URL: postgresql://chatuser:chatpass@postgres-chat:5432/chatdb
    # If you want to expose port:
    # ports:
    #   - "8002:8002"

  # ---------- Gateway ----------
  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
      CHAT_SERVICE_URL: "chat-service:8002"
      AUTH_SERVICE_URL: "auth-service:8003"
    ports:
      - "8001:8001"

volumes:
  postgres_auth_data:
  postgres_chat_data:
